# ~/.config/hypr/hyprpaper.conf
ipc = on
splash = false

# Optional default (used only at startup)
wallpaper {
    monitor = eDP-2
    path = /home/prem/Pictures/Wallpapers/Pokemon/reshiram_cropped.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/prem/Pictures/Wallpapers/Pokemon/Ho-Oh.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/prem/Pictures/Wallpapers/Pokemon/Ho-Oh.jpg
    fit_mode = cover
}
