-- Generated by nwg-displays on 2026-06-25 at 23:18:40. Do not edit manually.

hl.monitor({
    output = "eDP-2",
    mode = "2560x1600@165.04",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0
})
